# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-
top = '../..'

def build(bld):

    bld.program(
        target='../../bin/newndnpoke',
        source='new-ndn-poke.cpp',
        use='core-objects')

